/**
 * Column mapping to the SMCBI Health Kiosk's `users` table (see
 * database/migrations in that project - firstname, lastname, email, role,
 * department, grade_level, strand, year_level, program, birthday, gender,
 * barcode, student_id). barcode comes from what the person typed in at
 * registration - the same number already printed on their physical school
 * ID - rather than being generated by this export. For students, the
 * kiosk's own registration flow sets student_id equal to barcode
 * (AuthController::register), so this mirrors that here; personnel accounts
 * get a barcode but no student_id, same as on the kiosk side.
 *
 * Never includes password_hash or any authentication secret - the kiosk
 * creates its own credentials through its own registration/activation flow.
 */

const COLLEGE_PROGRAMS = new Set(['BSIT', 'BSED', 'BEED', 'BSHM', 'BSBA'])

/** This portal only collects two roles; the kiosk's own enum is finer. */
function kioskRole(registration) {
  if (registration.department === 'COLLEGE INSTRUCTOR' || registration.department === 'BED INSTRUCTOR') {
    return 'teacher'
  }
  if (registration.department === 'NTP') return 'personnel'
  return 'student'
}

export const EXPORT_COLUMNS = [
  'First Name',
  'Last Name',
  'Email',
  'Birthday',
  'Gender',
  'Role',
  'Department',
  'Grade Level',
  'Strand',
  'Year Level',
  'Program',
  'Barcode',
  'Student ID',
  'Status',
]

export function toExportRows(registrations) {
  return registrations.map((row) => ({
    'First Name': row.firstname,
    'Last Name': row.lastname,
    Email: row.email,
    Birthday: row.birthday,
    Gender: row.gender,
    Role: kioskRole(row),
    Department: row.department,
    'Grade Level': row.grade_level ?? '',
    Strand: row.strand ?? '',
    'Year Level': row.year_level ?? '',
    Program: COLLEGE_PROGRAMS.has(row.program) ? row.program : '',
    Barcode: row.barcode ?? '',
    'Student ID': row.role === 'student' ? (row.barcode ?? '') : '',
    Status: row.status,
  }))
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}

function csvEscape(value) {
  const text = String(value ?? '')
  if (/[",\n]/.test(text)) return `"${text.replace(/"/g, '""')}"`
  return text
}

export function exportCSV(registrations, filename = 'smcbi-approved-registrations.csv') {
  const rows = toExportRows(registrations)
  const lines = [
    EXPORT_COLUMNS.join(','),
    ...rows.map((row) => EXPORT_COLUMNS.map((column) => csvEscape(row[column])).join(',')),
  ]
  // BOM so Excel opens it as UTF-8 instead of guessing the system codepage.
  downloadBlob(new Blob(['﻿' + lines.join('\r\n')], { type: 'text/csv;charset=utf-8;' }), filename)
}

export async function exportExcel(registrations, filename = 'smcbi-approved-registrations.xlsx') {
  const ExcelJS = (await import('exceljs')).default
  const rows = toExportRows(registrations)

  const workbook = new ExcelJS.Workbook()
  workbook.creator = 'SMCBI Student Pre-Registration Portal'
  workbook.created = new Date()

  const sheet = workbook.addWorksheet('Approved Registrations')
  sheet.columns = EXPORT_COLUMNS.map((column) => ({ header: column, key: column, width: 18 }))
  sheet.getRow(1).font = { bold: true }
  sheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE5EDFF' } }
  rows.forEach((row) => sheet.addRow(row))
  sheet.autoFilter = { from: 'A1', to: `${String.fromCharCode(64 + EXPORT_COLUMNS.length)}1` }

  const buffer = await workbook.xlsx.writeBuffer()
  downloadBlob(
    new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }),
    filename,
  )
}

/**
 * @param targetWindow  A window opened synchronously in the click handler
 *                       (before the awaits above happen), so the browser
 *                       attributes it to the user gesture and doesn't treat
 *                       it as a blocked popup. Falls back to opening one
 *                       here if the caller didn't pass one.
 */
export async function exportPDF(registrations, filename = 'smcbi-approved-registrations.pdf', targetWindow = null) {
  const { jsPDF } = await import('jspdf')
  const autoTable = (await import('jspdf-autotable')).default
  const rows = toExportRows(registrations)

  const doc = new jsPDF({ orientation: 'landscape' })
  doc.setFontSize(14)
  doc.text('SMCBI - Approved Student Registrations', 14, 15)
  doc.setFontSize(9)
  doc.setTextColor(120)
  doc.text(`Generated ${new Date().toLocaleString('en-US')} - ${rows.length} record(s)`, 14, 21)

  autoTable(doc, {
    startY: 26,
    head: [EXPORT_COLUMNS],
    body: rows.map((row) => EXPORT_COLUMNS.map((column) => row[column] ?? '')),
    styles: { fontSize: 7, cellPadding: 2 },
    headStyles: { fillColor: [37, 99, 235] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  })

  doc.setProperties({ title: filename })
  const blobUrl = doc.output('bloburl')

  if (targetWindow && !targetWindow.closed) {
    targetWindow.location.href = blobUrl
  } else {
    window.open(blobUrl, '_blank')
  }
}

export async function exportDocx(registrations, filename = 'smcbi-approved-registrations.docx') {
  const { Document, Packer, Paragraph, Table, TableRow, TableCell, TextRun, HeadingLevel, WidthType } =
    await import('docx')
  const rows = toExportRows(registrations)

  const headerRow = new TableRow({
    tableHeader: true,
    children: EXPORT_COLUMNS.map(
      (column) =>
        new TableCell({
          width: { size: 100 / EXPORT_COLUMNS.length, type: WidthType.PERCENTAGE },
          children: [new Paragraph({ children: [new TextRun({ text: column, bold: true })] })],
        }),
    ),
  })

  const bodyRows = rows.map(
    (row) =>
      new TableRow({
        children: EXPORT_COLUMNS.map(
          (column) =>
            new TableCell({
              children: [new Paragraph(String(row[column] ?? ''))],
            }),
        ),
      }),
  )

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({ text: 'SMCBI - Approved Student Registrations', heading: HeadingLevel.HEADING_2 }),
          new Paragraph({
            text: `Generated ${new Date().toLocaleString('en-US')} - ${rows.length} record(s)`,
          }),
          new Paragraph({ text: '' }),
          new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [headerRow, ...bodyRows] }),
        ],
      },
    ],
  })

  const blob = await Packer.toBlob(doc)
  downloadBlob(blob, filename)
}
